const assert = require('assert');
const { parsePageMarker } = require('./helpers/loadAppModule')()('app_src/pageMarker.js');
assert.strictEqual(parsePageMarker(' Page 12 '), 12);
assert.strictEqual(parsePageMarker('page\t003'), 3);
for (const heading of ['Page 12 :', 'Page 12:', 'Page 12 -', 'Page 12.', '[Page 12]', '## Page 12', '### Page 12 ###', 'Page 12 : Title', 'Page 12 - End', 'Page 12 \u2013 Title']) assert.strictEqual(parsePageMarker(heading), 12);
for (const text of ['Read Page 12 now', 'Page 0', 'Page 3 notes', 'Page 9007199254740992', null]) assert.strictEqual(parsePageMarker(text), null);
const { reducer, initial } = require('./helpers/loadContext')();
let state = reducer(initial, { type: 'setText', text: 'Read Page 12 now\nPage 2\nDialogue' });
assert.strictEqual(!!state.lines[0].ignore, false);
assert.strictEqual(!!state.lines[1].ignore, true);
state = reducer(state, { type: 'addTab', data: { text: 'Second script' } });
const tabs = state.tabs;
const activeId = state.currentTabId;
state = reducer(state, { type: 'setMultiTabEnabled', value: false });
assert.deepStrictEqual(state.tabs, tabs);
assert.strictEqual(state.currentTabId, activeId);
state = reducer(state, { type: 'setMultiTabEnabled', value: true });
assert.deepStrictEqual(state.tabs, tabs);
console.log('Workspace navigation regression tests passed');
