const assert=require('assert'),fs=require('fs'),vm=require('vm'),React=require('react');
const loader=require('./helpers/loadAppModule'),ctx={};vm.createContext(ctx);vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../app_src/doubleBubbleGeometry.js'),'utf8'),ctx);
function harness(){
 const values=[],effects=[],queue=[],timers=new Map(),actions=[],calls=[];let index=0,dirty=true,tree,request,handler,id=0;
 const api={setAssisting:v=>calls.push(['pause',v]),requestAssistance:cb=>{request=cb;},applyAssistance:(data,cb,polygons)=>{calls.push(['apply',data,polygons]);api.reply=cb;}};
 const react={...React,memo:fn=>fn,useState(initial){const k=index++;if(!(k in values))values[k]=initial;return [values[k],next=>{const v=typeof next==='function'?next(values[k]):next;if(values[k]!==v){values[k]=v;dirty=true;}}];},useRef(initial){const k=index++;if(!(k in values))values[k]={current:initial};return values[k];},useEffect(fn,deps){const k=index++,old=effects[k];if(!old||deps.some((d,i)=>d!==old.deps[i])){effects[k]={deps,cleanup:old?.cleanup};queue.push(()=>{effects[k].cleanup?.();effects[k].cleanup=fn();});}}};
 const component=loader({'react':react,'./doubleBubbleAssist.scss':{},'../../utils':{locale:{}},'../../context':{useContext:()=>({dispatch:a=>actions.push(a)})},'../../modalClose':{useModalClose:cb=>{handler=cb;}}})('app_src/components/modal/doubleBubbleAssist.jsx').default;
 function flush(){let attempts=0;while(dirty||queue.length){if(++attempts>25)throw Error('render loop');if(dirty){dirty=false;index=0;global.window={TypeRDoubleBubble:ctx.TypeRDoubleBubble,TypeRDoubleBubbleBridge:api};global.setTimeout=(fn)=>{timers.set(++id,fn);return id;};global.clearTimeout=k=>timers.delete(k);tree=component();}while(queue.length)queue.shift()();}return tree;}
 function all(predicate,node=tree,found=[]){if(!node)return found;if(Array.isArray(node)){node.forEach(n=>{if(n!==undefined&&n!==null)all(predicate,n,found);});return found;}if(typeof node==='object'){if(predicate(node))found.push(node);if(node.props?.children)all(predicate,node.props.children,found);}return found;}
 return {api,calls,actions,flush,all,respond:data=>{request(JSON.stringify(data));flush();},finishPreview(){for(const [key,fn]of timers){timers.delete(key);fn();}flush();},click(x,y){const svg=all(n=>n.type==='svg')[0];svg.props.onClick({clientX:x*.75+200,clientY:y*.75+300,currentTarget:{getScreenCTM:()=>({inverse:()=>({})}),createSVGPoint:()=>({x:0,y:0,matrixTransform(){return {x:(this.x-200)/.75,y:(this.y-300)/.75};}})}});flush();},closeGuard:()=>{handler();flush();},dispose(){effects.forEach(e=>e?.cleanup?.());}};
}
const poly=Array.from({length:96},(_,i)=>[100*Math.cos(i*Math.PI/48),200*Math.sin(i*Math.PI/48)]),data={key:'k',documentID:7,polygons:[poly],points:[],offset:0};
const savedTimeout=global.setTimeout,savedClear=global.clearTimeout,savedWindow=global.window;
try{
 const h=harness();h.flush();h.respond(data);h.click(-50,0);h.click(50,0);
 let buttons=h.all(n=>n.type==='button'&&String(n.props.children).startsWith('Select half'));
 assert(buttons.every(b=>b.props.disabled),'no apply before calculation');h.finishPreview();buttons=h.all(n=>n.type==='button'&&String(n.props.children).startsWith('Select half'));assert(buttons.every(b=>!b.props.disabled));
 const sliders=h.all(n=>n.type==='input');sliders[0].props.onChange({target:{value:'20'}});h.flush();assert(h.all(n=>n.type==='button'&&String(n.props.children).startsWith('Select half')).every(b=>b.props.disabled),'old preview cannot be applied after line movement');h.finishPreview();
 h.all(n=>n.type==='button'&&n.props.children==='Select half 2')[0].props.onClick();h.flush();const call=h.calls.find(c=>c[0]==='apply');assert.equal(call[1].index,1);assert.equal(call[1].offset,.2);assert.equal(call[1].first.x,-50,'SVG transforms preserve document coordinates');assert.equal(call[2][0].length,poly.length);
 h.closeGuard();assert.equal(h.actions.length,0,'escape cannot close while host operation is pending');h.api.reply({changed:false,error:'selectionChanged'});h.flush();assert(h.all(n=>n.props?.role==='status').some(n=>String(n.props.children).includes('selection changed')));h.closeGuard();assert.equal(h.actions.length,1);h.dispose();assert.deepEqual(h.calls.at(-1),['pause',false]);
 const canceled=harness();canceled.flush();canceled.dispose();canceled.respond(data);assert.equal(canceled.calls.filter(c=>c[0]==='apply').length,0,'late probe after cancellation cannot apply a selection');
 const single=harness();single.flush();single.respond(data);single.all(n=>n.type==='button'&&n.props.children==='Keep one bubble')[0].props.onClick();single.flush();assert(single.calls.some(c=>c[0]==='apply'&&c[1].whole),'restore whole without two markers');single.api.reply({changed:true});single.flush();assert.equal(single.actions.length,1);single.dispose();
 console.log('Assist UI: transformed clicks, two markers, preview gating, sliders, half choice, stale selection, busy close guard and canceled probe PASS');
}finally{global.setTimeout=savedTimeout;global.clearTimeout=savedClear;global.window=savedWindow;}
